{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "60f215a1-c168-4f28-b755-4209d339d06c",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Statistical testing and regression modelling functions.\"\"\"\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from typing import Dict, Any, Optional\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.metrics import r2_score, mean_squared_error\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from scipy import stats\n",
    "from scipy.stats import pearsonr, spearmanr, ttest_ind\n",
    "\n",
    "# Spatial statistics (optional)\n",
    "SPATIAL_STATS_AVAILABLE = False\n",
    "try:\n",
    "    from esda.moran import Moran\n",
    "    from libpysal.weights import Queen\n",
    "    SPATIAL_STATS_AVAILABLE = True\n",
    "except ImportError:\n",
    "    print(\"Warning: PySAL not available - skipping Moran's I\")\n",
    "\n",
    "# GWR\n",
    "try:\n",
    "    from mgwr.gwr import GWR\n",
    "    from mgwr.sel_bw import Sel_BW\n",
    "    GWR_AVAILABLE = True\n",
    "except ImportError:\n",
    "    print(\"Warning: mgwr not available - skipping GWR\")\n",
    "    GWR_AVAILABLE = False\n",
    "\n",
    "def test_correlation(df: pd.DataFrame, var1: str, var2: str, alpha: float = 0.05) -> Dict[str, Any]:\n",
    "    \"\"\"Perform Pearson and Spearman correlation tests.\"\"\"\n",
    "    # Pearson (linear)\n",
    "    r_pearson, p_pearson = pearsonr(df[var1], df[var2])\n",
    "    # Spearman (rank-based)\n",
    "    r_spearman, p_spearman = spearmanr(df[var1], df[var2])\n",
    "    \n",
    "    results = {\n",
    "        'pearson_r': r_pearson,\n",
    "        'pearson_p': p_pearson,\n",
    "        'pearson_sig': p_pearson < alpha,\n",
    "        'spearman_r': r_spearman,\n",
    "        'spearman_p': p_spearman,\n",
    "        'spearman_sig': p_spearman < alpha,\n",
    "    }\n",
    "    return results\n",
    "\n",
    "def print_correlation_results(results: Dict[str, Any], var1: str, var2: str):\n",
    "    \"\"\"Print formatted correlation results.\"\"\"\n",
    "    print(f\"\\n1. Correlation Analysis: {var1} vs {var2}\")\n",
    "    print(f\"  Pearson: r={results['pearson_r']:.4f}, p={results['pearson_p']:.4f} \"\n",
    "          f\"({'Significant' if results['pearson_sig'] else 'Not significant'})\")\n",
    "    print(f\"  Spearman: r={results['spearman_r']:.4f}, p={results['spearman_p']:.4f} \"\n",
    "          f\"({'Significant' if results['spearman_sig'] else 'Not significant'})\")\n",
    "\n",
    "def perform_statistical_tests(reg_gdf: pd.DataFrame, config: dict) -> Dict[str, Any]:\n",
    "    \"\"\"Comprehensive statistical testing.\"\"\"\n",
    "    alpha = config['statistical']['significance_level']\n",
    "    \n",
    "    # Test 1: Correlation between log(crime) and log(median_price)\n",
    "    corr_results = test_correlation(reg_gdf, 'log_crime', 'log_median_price', alpha)\n",
    "    print_correlation_results(corr_results, 'log(Crime)', 'log(Price)')\n",
    "    \n",
    "    # Test 2: High-crime vs low-crime areas (t-test)\n",
    "    median_crime = reg_gdf['total_crimes'].median()\n",
    "    high_crime = reg_gdf[reg_gdf['total_crimes'] >= median_crime]['log_median_price']\n",
    "    low_crime = reg_gdf[reg_gdf['total_crimes'] < median_crime]['log_median_price']\n",
    "    \n",
    "    t_stat, p_value = ttest_ind(high_crime, low_crime)\n",
    "    \n",
    "    print(\"\\n2. Hypothesis Test: High-Crime vs Low-Crime Areas\")\n",
    "    print(\"H0: Mean log(price) is equal in high/low crime areas\")\n",
    "    print(\"H1: Mean log(price) differs between high/low crime areas\")\n",
    "    print(f\"  t-statistic: {t_stat:.4f}, p-value: {p_value:.4f}\")\n",
    "    \n",
    "    if p_value < alpha:\n",
    "        print(\"Result: REJECT H0 (p < α)\")\n",
    "        mean_diff = high_crime.mean() - low_crime.mean()\n",
    "        pct_diff = (np.exp(mean_diff) - 1) * 100\n",
    "        print(f\"High-crime areas are {pct_diff:.1f}% {'higher' if pct_diff > 0 else 'lower'} priced\")\n",
    "    else:\n",
    "        print(\"Result: FAIL TO REJECT H0 (p ≥ α)\")\n",
    "        print(\"Interpretation: No statistically significant difference\")\n",
    "    \n",
    "    test_results = {\n",
    "        'correlation': corr_results,\n",
    "        'ttest': {\n",
    "            't_statistic': t_stat,\n",
    "            'p_value': p_value,\n",
    "            'significant': p_value < alpha,\n",
    "            'high_crime_mean': high_crime.mean(),\n",
    "            'low_crime_mean': low_crime.mean(),\n",
    "        }\n",
    "    }\n",
    "    return test_results\n",
    "\n",
    "def fit_ols_model(reg_gdf: pd.DataFrame) -> Dict[str, Any]:\n",
    "    \"\"\"Fit global OLS regression model (baseline).\"\"\"\n",
    "    print(\"\\n1. ORDINARY LEAST SQUARES (OLS) REGRESSION - GLOBAL MODEL\")\n",
    "    \n",
    "    # Prepare data: log_price ~ log_crime + prop_flats + prop_leasehold\n",
    "    y = reg_gdf['log_median_price'].values.reshape(-1, 1)\n",
    "    X = reg_gdf[['log_crime', 'prop_flats', 'prop_leasehold']].values\n",
    "    \n",
    "    # Fit OLS\n",
    "    ols = LinearRegression()\n",
    "    ols.fit(X, y)\n",
    "    \n",
    "    # Predictions and residuals\n",
    "    y_pred = ols.predict(X)\n",
    "    residuals = y.ravel() - y_pred.ravel()\n",
    "    \n",
    "    # Metrics\n",
    "    r2 = r2_score(y, y_pred)\n",
    "    n, k = len(y), X.shape[1] + 1  # +1 for intercept\n",
    "    adj_r2 = 1 - (1 - r2) * (n - 1) / (n - k)\n",
    "    mse = mean_squared_error(y, y_pred)\n",
    "    rss = np.sum(residuals**2)\n",
    "    aic = n * np.log(rss/n) + 2 * k\n",
    "    aicc = aic + 2 * k * (k + 1) / (n - k - 1)\n",
    "    \n",
    "    print(\"log_price = β0 + β1*log_crime + β2*prop_flats + β3*prop_leasehold\")\n",
    "    print()\n",
    "    print(f\"  Intercept:     {ols.intercept_[0]:.4f}\")\n",
    "    print(f\"  log_crime:     {ols.coef_[0][0]:.4f}\")\n",
    "    print(f\"  prop_flats:    {ols.coef_[0][1]:.4f}\")\n",
    "    print(f\"  prop_leasehold:{ols.coef_[0][2]:.4f}\")\n",
    "    print(f\"\\nFit Statistics:\")\n",
    "    print(f\"  R²:            {r2:.4f}\")\n",
    "    print(f\"  Adj R²:        {adj_r2:.4f}\")\n",
    "    print(f\"  AIC:           {aic:.2f}\")\n",
    "    print(f\"  AICc:          {aicc:.2f}\")\n",
    "    print(f\"  RMSE:          {np.sqrt(mse):.4f}\")\n",
    "    \n",
    "    # Crime effect interpretation (% change)\n",
    "    crime_effect_pct = (np.exp(ols.coef_[0][0]) - 1) * 100\n",
    "    print(f\"A 1-unit increase in log(crime) → {crime_effect_pct:.2f}% change in price\")\n",
    "    \n",
    "    return {\n",
    "        'model': ols,\n",
    "        'y_pred': y_pred.ravel(),\n",
    "        'residuals': residuals,\n",
    "        'r2': r2,\n",
    "        'adj_r2': adj_r2,\n",
    "        'aic': aic,\n",
    "        'aicc': aicc,\n",
    "        'rmse': float(np.sqrt(mse)),\n",
    "        'coefficients': {\n",
    "            'intercept': float(ols.intercept_[0]),\n",
    "            'log_crime': float(ols.coef_[0][0]),\n",
    "            'prop_flats': float(ols.coef_[0][1]),\n",
    "            'prop_leasehold': float(ols.coef_[0][2]),\n",
    "        }\n",
    "    }\n",
    "\n",
    "def fit_gwr_model(reg_gdf: pd.GeoDataFrame, config: dict) -> Optional[Dict[str, Any]]:\n",
    "    \"\"\"Fit Geographically Weighted Regression (GWR) model.\"\"\"\n",
    "    if not GWR_AVAILABLE:\n",
    "        print(\"GWR not available (mgwr not installed)\")\n",
    "        return None\n",
    "    \n",
    "    print(\"\\n3. GEOGRAPHICALLY WEIGHTED REGRESSION (GWR)\")\n",
    "    \n",
    "    # Extract coordinates\n",
    "    coords = np.column_stack([\n",
    "        reg_gdf.geometry.centroid.x,\n",
    "        reg_gdf.geometry.centroid.y\n",
    "    ])\n",
    "    \n",
    "    # Outcome and predictors (same as OLS)\n",
    "    y = reg_gdf['log_median_price'].values.reshape(-1, 1)\n",
    "    X = reg_gdf[['log_crime', 'prop_flats', 'prop_leasehold']].values\n",
    "    \n",
    "    print(f\"Input shape: coords={coords.shape}, y={y.shape}, X={X.shape}\")\n",
    "    \n",
    "    if len(reg_gdf) < 30:\n",
    "        print(\"Too few LSOAs for stable GWR fit\")\n",
    "        return None\n",
    "    \n",
    "    # Bandwidth selection\n",
    "    print(\"Bandwidth selection...\")\n",
    "    try:\n",
    "        bw = Sel_BW(coords, y, X).search()\n",
    "        print(f\"Bandwidth: {bw:.1f}\")\n",
    "    except Exception:\n",
    "        print(\"Bandwidth selection failed - using fixed fallback\")\n",
    "        bw = 50  # adaptive fallback\n",
    "    \n",
    "    # Fit GWR\n",
    "    print(\"Fitting GWR...\")\n",
    "    try:\n",
    "        gwr_model = GWR(coords, y, X, bw=bw).fit()\n",
    "        print(gwr_model.summary())\n",
    "        \n",
    "        return {\n",
    "            'model': gwr_model,\n",
    "            'bw': bw,\n",
    "            'r2': gwr_model.R2,\n",
    "            'adj_r2': gwr_model.adjR2,\n",
    "            'aic': gwr_model.aic,\n",
    "            'aicc': gwr_model.aicc,\n",
    "            'params': gwr_model.params,  # Local coefficients for each LSOA\n",
    "        }\n",
    "    except Exception as e:\n",
    "        print(f\"GWR failed: {e}\")\n",
    "        return None\n",
    "\n",
    "def calculate_morans_i(reg_gdf: pd.GeoDataFrame, residuals: np.ndarray) -> Optional[Dict[str, Any]]:\n",
    "    \"\"\"Calculate Moran's I to test spatial autocorrelation in residuals.\"\"\"\n",
    "    if not SPATIAL_STATS_AVAILABLE:\n",
    "        print(\"PySAL not available - skipping Moran's I\")\n",
    "        return None\n",
    "    \n",
    "    print(\"\\nCalculating Moran's I (spatial autocorrelation)...\")\n",
    "    \n",
    "    try:\n",
    "        w = Queen.from_dataframe(reg_gdf)\n",
    "        w.transform = 'r'\n",
    "        moran = Moran(residuals, w)\n",
    "        \n",
    "        print(f\"Moran's I: {moran.I:.4f}\")\n",
    "        print(f\"Expected I: {moran.EI:.4f}\")\n",
    "        print(f\"p-value: {moran.p_sim:.4f}\")\n",
    "        \n",
    "        return {\n",
    "            'I': moran.I,\n",
    "            'EI': moran.EI,\n",
    "            'p_value': moran.p_sim,\n",
    "            'significant': moran.p_sim < 0.05,\n",
    "        }\n",
    "    except Exception as e:\n",
    "        print(f\"Moran's I failed: {e}\")\n",
    "        return None\n",
    "\n",
    "def compare_models(\n",
    "    ols_results: Dict[str, Any], \n",
    "    gwr_results: Optional[Dict[str, Any]], \n",
    "    reg_gdf: pd.GeoDataFrame\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"Compare OLS vs GWR models.\"\"\"\n",
    "    print(\"\\nSTEP 8: MODEL COMPARISON (OLS vs GWR)\")\n",
    "    \n",
    "    # OLS results\n",
    "    print(\"1. OLS Results\")\n",
    "    print(f\"   R²:     {ols_results['r2']:.4f}\")\n",
    "    print(f\"   Adj R²: {ols_results['adj_r2']:.4f}\")\n",
    "    print(f\"   AICc:   {ols_results['aicc']:.2f}\")\n",
    "    print(f\"   Crime effect: {ols_results['coefficients']['log_crime']:.4f}\")\n",
    "    \n",
    "    if gwr_results is None:\n",
    "        print(\"2. GWR Results: unavailable (GWR failed)\")\n",
    "        return {'comparison_table': None, 'gwr_available': False}\n",
    "    \n",
    "    # GWR results\n",
    "    print(\"2. GWR Results\")\n",
    "    print(f\"   R²:     {gwr_results['r2']:.4f}\")\n",
    "    print(f\"   Adj R²: {gwr_results['adj_r2']:.4f}\")\n",
    "    print(f\"   AICc:   {gwr_results['aicc']:.2f}\")\n",
    "    crime_coefs = gwr_results['params'][:, 1]  # log_crime column\n",
    "    print(f\"   Crime coef range: {crime_coefs.min():.4f} to {crime_coefs.max():.4f}\")\n",
    "    \n",
    "    # Build comparison table\n",
    "    comparison = pd.DataFrame({\n",
    "        'Metric': ['R²', 'Adj R²', 'AICc'],\n",
    "        'OLS': [ols_results['r2'], ols_results['adj_r2'], ols_results['aicc']],\n",
    "        'GWR': [gwr_results['r2'], gwr_results['adj_r2'], gwr_results['aicc']],\n",
    "    })\n",
    "    \n",
    "    improvement = comparison['GWR'] - comparison['OLS']\n",
    "    comparison['GWR Better'] = ['Yes' if imp < 0 or imp > 0 else 'No' \n",
    "                               for imp in improvement]  # AIC lower=better, R2 higher=better\n",
    "    \n",
    "    print(\"\\nComparison Table:\")\n",
    "    print(comparison.round(4).to_string(index=False))\n",
    "    \n",
    "    return {\n",
    "        'comparison_table': comparison,\n",
    "        'gwr_available': True,\n",
    "    }\n",
    "\n",
    "def run_full_analysis_pipeline(reg_gdf: pd.GeoDataFrame, config: dict) -> Dict[str, Any]:\n",
    "    \"\"\"Run complete analysis pipeline (formerly runfullanalysis).\"\"\"\n",
    "    results = {}\n",
    "    \n",
    "    # Statistical tests\n",
    "    results['test_results'] = perform_statistical_tests(reg_gdf, config)\n",
    "    \n",
    "    # OLS model\n",
    "    results['ols_results'] = fit_ols_model(reg_gdf)\n",
    "    \n",
    "    # Moran's I on OLS residuals\n",
    "    results['morans_results'] = calculate_morans_i(reg_gdf, results['ols_results']['residuals'])\n",
    "    \n",
    "    # GWR model\n",
    "    results['gwr_results'] = fit_gwr_model(reg_gdf, config)\n",
    "    \n",
    "    # Model comparison\n",
    "    results['comparison_results'] = compare_models(\n",
    "        results['ols_results'], results['gwr_results'], reg_gdf\n",
    "    )\n",
    "    \n",
    "    return results\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
