{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "efbff7a6-7696-4633-a7cf-d3b989983530",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Data loading, cleaning, and aggregation functions.\"\"\"\n",
    "\n",
    "import pandas as pd\n",
    "import geopandas as gpd\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "from typing import Tuple\n",
    "from src.config import config\n",
    "\n",
    "def load_house_price_data(datapath: Path, startyear: int = 2021, endyear: int = 2024) -> pd.DataFrame:\n",
    "    \"\"\"Load and concatenate HM Land Registry house price data for Bristol.\"\"\"\n",
    "    print(\"1. Loading house price data from\", datapath)\n",
    "    \n",
    "    column_names = [\n",
    "        'transaction_id', 'price', 'date', 'postcode', 'property_type',
             'new_build_flag', 'tenure_type', 'paon', 'saon', 'street',
             'locality', 'town_city', 'district', 'county',
             'ppd_category', 'record_status'\n",
    "    ]\n",
    "    \n",
    "    csv_files = list(datapath.glob(\"pp-*.csv\"))\n",
    "    if len(csv_files) == 0:\n",
    "        raise FileNotFoundError(f\"No house price files found in {data_path}.\")\n",
    "    \n",
    "    print(f\"Found {len(csv_files)} CSV files\")\n",
    "    \n",
    "    dataframes = []\n",
    "    for file in csv_files:\n",
    "        try:\n",
    "            df = pd.read_csv(file, header=None, names=column_names, low_memory=False)\n",
    "            dataframes.append(df)\n",
    "        except Exception as e:\n",
    "            print(f\"Error loading {file.name}: {e}\")\n",
    "            continue\n",
    "    \n",
    "    if len(dataframes) == 0:\n",
    "        raise ValueError(\"No valid house price data loaded\")\n",
    "    \n",
    "    house_data = pd.concat(dataframes, ignore_index=True)\n",
    "    house_data['date'] = pd.to_datetime(house_data['date'], errors='coerce')\n",
    "    house_data['year'] = house_data['date'].dt.year\n",
    "    \n",
    "    house_data = house_data[\n",
    "        (house_data['year'] >= start_year) & (house_data['year'] <= end_year)\n",
    "    ].copy()\n",
    "    \n",
    "    print(f\"Loaded {len(house_data)} transactions {start_year}-{end_year}\")\n",
    "    print(f\"Date range: {house_data['date'].min()} to {house_data['date'].max()}\")\n",
    "    return house_data\n",
    "\n",
    "def load_crime_data(datapath: Path, start_year: int = 2021, end_year: int = 2024) -> pd.DataFrame:\n",
    "    \"\"\"Load and concatenate monthly Police.uk crime data for Bristol.\"\"\"\n",
    "    print(\"2. Loading crime data from\", data_path)\n",
    "    \n",
    "    csv_files = list(data_path.rglob(\"*.csv\"))\n",
    "    if len(csv_files) == 0:\n",
    "        raise FileNotFoundError(f\"No crime files found in {data_path}\")\n",
    "    \n",
    "    print(f\"Found {len(csv_files)} CSV files\")\n",
    "    \n",
    "    dataframes = []\n",
    "    for file in csv_files:\n",
    "        try:\n",
    "            df = pd.read_csv(file, low_memory=False)\n",
    "            dataframes.append(df)\n",
    "        except Exception as e:\n",
    "            print(f\"Error loading {file.name}: {e}\")\n",
    "            continue\n",
    "    \n",
    "    if len(dataframes) == 0:\n",
    "        raise ValueError(\"No valid crime data loaded\")\n",
    "    \n",
    "    crime_data = pd.concat(dataframes, ignore_index=True)\n",
    "    crime_data['Month'] = pd.to_datetime(crime_data['Month'], errors='coerce')\n",
    "    crime_data['year'] = crime_data['Month'].dt.year\n",
    "    \n",
    "    crime_data = crime_data[\n",
    "        (crime_data['year'] >= start_year) & (crime_data['year'] <= end_year)\n",
    "    ].copy()\n",
    "    \n",
    "    print(f\"Loaded {len(crime_data)} crime records {start_year}-{end_year}\")\n",
    "    print(f\"Unique crime types: {crime_data['Crime type'].nunique()}\")\n",
    "    return crime_data\n",
    "\n",
    "def load_geospatial_data(geo_path: Path) -> Tuple[gpd.GeoDataFrame, pd.DataFrame]:\n",
    "    \"\"\"Load LSOA boundary polygons and postcode-to-LSOA lookup.\"\"\"\n",
    "    print(\"3. Loading geospatial data from\", geo_path)\n",
    "    \n",
    "    # 1. LSOA boundaries\n",
    "    lsoa_shp_files = list(geo_path.rglob(\"Lower_Layer_Super_Output_Areas*Precise*.shp\"))\n",
    "    if len(lsoa_shp_files) == 0:\n",
    "        lsoa_shp_files = list(geo_path.rglob(\"*.shp\"))\n",
    "    if len(lsoa_shp_files) == 0:\n",
    "        raise FileNotFoundError(f\"No LSOA shapefile found under {geo_path}\")\n",
    "    \n",
    "    lsoa_file = lsoa_shp_files[0]\n",
    "    print(f\"Using LSOA file: {lsoa_file}\")\n",
    "    lsoa_gdf = gpd.read_file(lsoa_file)\n",
    "    \n",
    "    # Standardise column names\n",
    "    lsoa_column_mappings = {\n",
    "        'LSOA21CD': 'lsoacode',\n",
    "        'LSOA Code': 'lsoacode',\n",
    "        'lsoa21cd': 'lsoacode',\n",
    "        'LSOA21NM': 'lsoaname',\n",
    "        'LSOA Name': 'lsoaname',\n",
    "    }\n",
    "    for old_col, new_col in lsoa_column_mappings.items():\n",
    "        if old_col in lsoa_gdf.columns:\n",
    "            lsoa_gdf = lsoa_gdf.rename(columns={old_col: new_col})\n",
    "    \n",
    "    print(f\"Loaded {len(lsoa_gdf)} LSOA polygons\")\n",
    "    \n",
    "    # 2. Postcode-to-LSOA lookup\n",
    "    postcode_files = list(geo_path.glob(\"postcode_directory.csv\"))\n",
    "    if len(postcode_files) == 0:\n",
    "        raise FileNotFoundError(f\"No postcode lookup file found in {geo_path}\")\n",
    "    \n",
    "    postcode_file = postcode_files[0]\n",
    "    print(f\"Using postcode file: {postcode_file}\")\n",
    "    postcode_df = pd.read_csv(postcode_file, low_memory=False)\n",
    "    \n",
    "    postcode_column_mappings = {\n",
    "        'pcds': 'postcode',\n",
    "        'Postcode': 'postcode',\n",
    "        'lsoa21cd': 'lsoacode',\n",
    "        'LSOA Code': 'lsoacode',\n",
    "    }\n",
    "    for old_col, new_col in postcode_column_mappings.items():\n",
    "        if old_col in postcode_df.columns:\n",
    "            postcode_df = postcode_df.rename(columns={old_col: new_col})\n",
    "    \n",
    "    print(f\"Loaded {len(postcode_df)} postcode-to-LSOA mappings\")\n",
    "    return lsoa_gdf, postcode_df\n",
    "\n",
    "def clean_house_prices(house_data: pd.DataFrame, config: dict) -> pd.DataFrame:\n",
    "    \"\"\"Clean and filter house price data for Bristol.\"\"\"\n",
    "    print(\"1. Cleaning house price data...\")\n",
    "    df = house_data.copy()\n",
    "    initial_count = len(df)\n",
    "    \n",
    "    # 1. Filter for Bristol district\n",
    "    df = df[df['district'].str.upper().str.contains(config['geographic']['bristol_district'], na=False)].copy()\n",
    "    print(f\"Filtered to {config['geographic']['bristol_district']}: {len(df)} records\")\n",
    "    \n",
    "    # 2. Standardise price and postcode\n",
    "    df['price'] = pd.to_numeric(df['price'], errors='coerce')\n",
    "    df['postcode'] = df['postcode'].astype(str).str.strip().str.upper()\n",
    "    \n",
    "    # 3. Remove rows with missing critical fields\n",
    "    required_fields = ['price', 'date', 'postcode', 'property_type']\n",
    "    before_missing = len(df)\n",
    "    df = df.dropna(subset=required_fields)\n",
    "    print(f\"Removed {before_missing - len(df)} rows with missing data\")\n",
    "    \n",
    "    # 4. Remove clearly invalid prices\n",
    "    df = df[df['price'] >= 100]\n",
    "    \n",
    "    # 5. Remove outliers using IQR rule\n",
    "    Q1 = df['price'].quantile(0.25)\n",
    "    Q3 = df['price'].quantile(0.75)\n",
    "    IQR = Q3 - Q1\n",
    "    lower_bound = Q1 - config['statistical']['iqr_multiplier'] * IQR\n",
    "    upper_bound = Q3 + config['statistical']['iqr_multiplier'] * IQR\n",
    "    \n",
    "    before_outlier = len(df)\n",
    "    df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]\n",
    "    print(f\"Removed {before_outlier - len(df)} outliers (IQR method)\")\n",
    "    print(f\"Price range: £{df['price'].min():,.0f} - £{df['price'].max():,.0f}\")\n",
    "    print(f\"Median price: £{df['price'].median():,.0f}\")\n",
    "    \n",
    "    retention_rate = len(df) / initial_count * 100\n",
    "    print(f\"Final: {len(df)} records ({retention_rate:.1f}% retained)\")\n",
    "    return df\n",
    "\n",
    "def clean_crime_data(crime_data: pd.DataFrame, config: dict) -> pd.DataFrame:\n",
    "    \"\"\"Clean and filter Police.uk crime data for Bristol.\"\"\"\n",
    "    print(\"2. Cleaning crime data...\")\n",
    "    df = crime_data.copy()\n",
    "    initial_count = len(df)\n",
    "    \n",
    "    # 1. Filter for Bristol LSOA codes\n",
    "    df = df[df['LSOA code'].astype(str).str.startswith(config['geographic']['bristol_lsoa_prefix'], na=False)].copy()\n",
    "    print(f\"Filtered to Bristol LSOA codes: {len(df)} records\")\n",
    "    \n",
    "    # 2. Convert coordinates to numeric\n",
    "    df['Latitude'] = pd.to_numeric(df['Latitude'], errors='coerce')\n",
    "    df['Longitude'] = pd.to_numeric(df['Longitude'], errors='coerce')\n",
    "    \n",
    "    # 3. Filter by geographic extent\n",
    "    before_geo = len(df)\n",
    "    df = df[\n",
    "        (df['Latitude'] >= config['geographic']['latmin']) &\n",
    "        (df['Latitude'] <= config['geographic']['latmax']) &\n",
    "        (df['Longitude'] >= config['geographic']['lonmin']) &\n",
    "        (df['Longitude'] <= config['geographic']['lonmax'])\n",
    "    ]\n",
    "    print(f\"Geographic filtering: {before_geo - len(df)} records removed\")\n",
    "    \n",
    "    # 4. Remove records with missing important fields\n",
    "    required_fields = ['Month', 'Crime type', 'LSOA code', 'Latitude', 'Longitude']\n",
    "    before_missing = len(df)\n",
    "    df = df.dropna(subset=required_fields)\n",
    "    print(f\"Removed {before_missing - len(df)} rows with missing data\")\n",
    "    \n",
    "    # 5. Remove duplicates\n",
    "    before_dup = len(df)\n",
    "    df = df.drop_duplicates()\n",
    "    print(f\"Removed {before_dup - len(df)} duplicate records\")\n",
    "    \n",
    "    # 6. Rename for consistency\n",
    "    df = df.rename(columns={'LSOA code': 'lsoacode'})\n",
    "    \n",
    "    retention_rate = len(df) / initial_count * 100\n",
    "    print(f\"Final: {len(df)} records ({retention_rate:.1f}% retained)\")\n",
    "    print(f\"Unique LSOAs: {df['lsoacode'].nunique()}\")\n",
    "    print(f\"Unique crime types: {df['Crime type'].nunique()}\")\n",
    "    return df\n",
    "\n",
    "def aggregate_house_prices_by_lsoa(house_clean: pd.DataFrame, postcode_lookup: pd.DataFrame) -> pd.DataFrame:\n",
    "    \"\"\"Aggregate cleaned house price data to LSOA level.\"\"\"\n",
    "    print(\"1. Aggregate House Price by LSOA\")\n",
    "    \n",
    "    # Standardise postcode format\n",
    "    house_clean['postcode_clean'] = house_clean['postcode'].astype(str).str.strip().str.upper()\n",
    "    postcode_lookup['postcode_clean'] = postcode_lookup['postcode'].astype(str).str.strip().str.upper()\n",
    "    \n",
    "    # Merge with LSOA codes\n",
    "    house_lsoa = house_clean.merge(\n",
    "        postcode_lookup[['postcode_clean', 'lsoacode']],\n",
    "        on='postcode_clean', how='left'\n",
    "    )\n",
    "    \n",
    "    # Check merge success\n",
    "    merge_rate = house_lsoa['lsoacode'].notna().sum() / len(house_lsoa) * 100\n",
    "    print(f\"Matched {merge_rate:.1f}% of house records to LSOA codes\")\n",
    "    \n",
    "    # Drop unmatched records\n",
    "    house_lsoa = house_lsoa.dropna(subset=['lsoacode'])\n",
    "    \n",
    "    # Create indicator variables\n",
    "    house_lsoa['is_flat'] = (house_lsoa['property_type'] == 'F').astype(int)\n",
    "    house_lsoa['is_leasehold'] = (house_lsoa['tenure_type'] == 'L').astype(int)\n",
    "    \n",
    "    # Aggregate to LSOA level\n",
    "    lsoa_agg = house_lsoa.groupby('lsoacode').agg(\n",
    "        median_price=('price', 'median'),\n",
    "        mean_price=('price', 'mean'),\n",
    "        n_sales=('price', 'size'),\n",
    "        flat_count=('is_flat', 'sum'),\n",
    "        leasehold_count=('is_leasehold', 'sum')\n",
    "    ).reset_index()\n",
    "    \n",
    "    # Calculate proportions\n",
    "    lsoa_agg['prop_flats'] = lsoa_agg['flat_count'] / lsoa_agg['n_sales']\n",
    "    lsoa_agg['prop_leasehold'] = lsoa_agg['leasehold_count'] / lsoa_agg['n_sales']\n",
    "    \n",
    "    print(f\"Aggregated to {len(lsoa_agg)} LSOAs\")\n",
    "    print(f\"Mean sales per LSOA: {lsoa_agg['n_sales'].mean():.1f}\")\n",
    "    return lsoa_agg\n",
    "\n",
    "def aggregate_crime_by_lsoa(crime_clean: pd.DataFrame) -> pd.DataFrame:\n",
    "    \"\"\"Aggregate crime counts to LSOA level.\"\"\"\n",
    "    print(\"2. Aggregate Crime by LSOA\")\n",
    "    \n",
    "    crime_agg = crime_clean.groupby('lsoa_code').size().reset_index(name='total_crimes')\n",
    "    \n",
    "    print(f\"Aggregated to {len(crime_agg)} LSOAs\")\n",
    "    print(f\"Mean crimes per LSOA: {crime_agg['total_crimes'].mean():.1f}\")\n",
    "    print(f\"Range: {crime_agg['total_crimes'].min()} - {crime_agg['total_crimes'].max()}\")\n",
    "    return crime_agg\n",
    "\n",
    "def create_regression_dataset(\n",
    "    lsoa_house: pd.DataFrame, \n",
    "    lsoa_crime: pd.DataFrame, \n",
    "    lsoa_gdf: gpd.GeoDataFrame\n",
    ") -> gpd.GeoDataFrame:\n",
    "    \"\"\"Merge house price, crime, and spatial data into final regression dataset.\"\"\"\n",
    "    \n",
    "    # Merge house prices and crime counts\n",
    "    reg_df = lsoa_house.merge(lsoa_crime, on='lsoa_code', how='inner')\n",
    "    print(f\"After merging house+crime: {len(reg_df)} LSOAs\")\n",
    "    \n",
    "    # Ensure LSOA code column name in spatial data is standardised\n",
    "    if 'lsoacode' not in lsoa_gdf.columns:\n",
    "        for col in ['LSOA21CD', 'lsoa21cd', 'LSOA Code']:\n",
    "            if col in lsoa_gdf.columns:\n",
    "                lsoa_gdf = lsoa_gdf.rename(columns={col: 'lsoa_code'})\n",
    "                break\n",
    "    \n",
    "    # Merge with spatial geometries\n",
    "    reg_gdf = lsoa_gdf.merge(reg_df, on='lsoa_code', how='inner')\n",
    "    print(f\"After merging with spatial data: {len(reg_gdf)} LSOAs\")\n",
    "    \n",
    "    # Add log-transformed variables\n",
    "    reg_gdf['log_median_price'] = np.log(reg_gdf['median_price'])\n",
    "    reg_gdf['log_crime'] = np.log(reg_gdf['total_crimes'] + 1)  # +1 to avoid log(0)\n",
    "    \n",
    "    # Drop any remaining missing values in key predictors\n",
    "    before_drop = len(reg_gdf)\n",
    "    reg_gdf = reg_gdf.dropna(subset=['log_median_price', 'log_crime', 'prop_flats', 'prop_leasehold'])\n",
    "    \n",
    "    if before_drop != len(reg_gdf):\n",
    "        print(f\"Dropped {before_drop - len(reg_gdf)} LSOAs with missing values\")\n",
    "    \n",
    "    print(f\"Final dataset: {len(reg_gdf)} LSOAs ready for analysis\")\n",
    "    return reg_gdf\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
