{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c5fd80d-8ac4-492c-8522-eb07612f7a51",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "Bristol House Prices & Crime Analysis Pipeline\n",
    "Spatial Analysis Using Geographically Weighted Regression (GWR)\n",
    "\n",
    "Usage:\n",
    "    python main.py\n",
    "\n",
    "This orchestrates the complete analysis:\n",
    "1. Load raw data (house prices, crime, geospatial)\n",
    "2. Clean and aggregate to LSOA level\n",
    "3. Statistical tests + OLS/GWR models\n",
    "4. Generate all visualizations\n",
    "5. Save results and summary\n",
    "\"\"\"\n",
    "\n",
    "import sys\n",
    "from pathlib import Path\n",
    "from typing import Dict, Any\n",
    "\n",
    "from src.config import CONFIG, RAW_DATA_PATH, PROCESSED_DATA_PATH, OUTPUT_PATH\n",
    "from src import data_processing as dp\n",
    "from src import analysis as an\n",
    "from src import visualization as viz\n",
    "\n",
    "def print_banner():\n",
    "    \"\"\"Print project banner.\"\"\"\n",
    "    banner = \"\"\"\n",
    "╔══════════════════════════════════════════════════════════════════════════════╗\n",
    "║                      BRISTOL HOUSE PRICES & CRIME                           ║\n",
    "║                    Spatial Analysis Using GWR                               ║\n",
    "║                    ==================================                       ║\n",
    "║                                                                              ║\n",
    "║  Analysis Period: 2021-2024  |  Geographic Scope: Bristol                   ║\n",
    "║  Models: OLS (global) vs GWR (local)                                        ║\n",
    "╚══════════════════════════════════════════════════════════════════════════════╝\n",
    "    \"\"\"\n",
    "    print(banner)\n",
    "\n",
    "def main():\n",
    "    \"\"\"Main analysis pipeline.\"\"\"\n",
    "    print_banner()\n",
    "    \n",
    "    try:\n",
    "        # ==================== STEP 1: LOAD RAW DATA ====================\n",
    "        print(\"\\n STEP 1: LOADING DATA\")\n",
    "        \n",
    "        house_raw = dp.load_house_price_data(RAW_DATA_PATH / \"houseprices\")\n",
    "        crime_raw = dp.load_crime_data(RAW_DATA_PATH / \"crime\")\n",
    "        lsoa_gdf, postcode_lookup = dp.load_geospatial_data(RAW_DATA_PATH / \"geo\")\n",
    "        \n",
    "        # ==================== STEP 2: CLEAN & PROCESS ====================\n",
    "        print(\"\\n STEP 2: CLEANING & PROCESSING\")\n",
    "        \n",
    "        house_clean = dp.clean_house_prices(house_raw, CONFIG)\n",
    "        crime_clean = dp.clean_crime_data(crime_raw, CONFIG)\n",
    "        \n",
    "        lsoa_house = dp.aggregate_house_prices_by_lsoa(house_clean, postcode_lookup)\n",
    "        lsoa_crime = dp.aggregate_crime_by_lsoa(crime_clean)\n",
    "        reg_gdf = dp.create_regression_dataset(lsoa_house, lsoa_crime, lsoa_gdf)\n",
    "        \n",
    "        # Save processed data\n",
    "        reg_gdf.to_file(PROCESSED_DATA_PATH / \"regression_dataset.geojson\", driver='GeoJSON')\n",
    "        print(f\" Processed dataset saved: {len(reg_gdf)} LSOAs\")\n",
    "        \n",
    "        # ==================== STEP 3: STATISTICAL ANALYSIS ====================\n",
    "        print(\"\\n STEP 3: STATISTICAL ANALYSIS & MODELLING\")\n",
    "        \n",
    "        results = an.run_full_analysis_pipeline(reg_gdf, CONFIG)\n",
    "        \n",
    "        # ==================== STEP 4: VISUALIZATIONS ====================\n",
    "        print(\"\\n STEP 4: GENERATING VISUALIZATIONS\")\n",
    "        \n",
    "        viz.create_visualization_suite(reg_gdf, results, house_clean, crime_clean)\n",
    "        \n",
    "        # ==================== STEP 5: SAVE RESULTS ====================\n",
    "        print(\"\\n STEP 5: SAVING RESULTS\")\n",
    "        \n",
    "        # Save model results\n",
    "        results_df = pd.DataFrame([{\n",
    "            'r2_ols': results['ols_results']['r2'],\n",
    "            'r2_gwr': results['gwr_results']['r2'] if results['gwr_results'] else None,\n",
    "            'aic_ols': results['ols_results']['aic'],\n",
    "            'aic_gwr': results['gwr_results']['aic'] if results['gwr_results'] else None,\n",
    "            'crime_coef_global': results['ols_results']['coefficients']['log_crime'],\n",
    "        }])\n",
    "        results_df.to_csv(OUTPUT_PATH / 'model_summary.csv', index=False)\n",
    "        \n",
    "        # Add GWR coefficients to GeoDataFrame and save\n",
    "        if results['gwr_results']:\n",
    "            reg_gdf['gwr_crime_coef'] = results['gwr_results']['params'][:, 1]\n",
    "            reg_gdf.to_file(OUTPUT_PATH / 'gwr_results.geojson', driver='GeoJSON')\n",
    "        \n",
    "        # ==================== STEP 6: EXECUTIVE SUMMARY ====================\n",
    "        print(\" EXECUTIVE SUMMARY\")\n",
    "        print(f\" Dataset: {len(reg_gdf)} LSOAs analyzed\")\n",
    "        print(f\" OLS R²: {results['ols_results']['r2']:.3f}\")\n",
    "        \n",
    "        if results['gwr_results']:\n",
    "            gwr_r2 = results['gwr_results']['r2']\n",
    "            print(f\" GWR R²: {gwr_r2:.3f} ({((gwr_r2/results['ols_results']['r2']-1)*100):+.1f}% improvement)\")\n",
    "            print(f\" Crime effect varies: {results['gwr_results']['params'][:,1].min():.3f} to {results['gwr_results']['params'][:,1].max():.3f}\")\n",
    "        \n",
    "        crime_effect = results['ols_results']['coefficients']['log_crime']\n",
    "        pct_effect = (np.exp(crime_effect) - 1) * 100\n",
    "        print(f\" Global crime effect: {crime_effect:.3f} ({pct_effect:.1f}% per log unit)\")\n",
    "        \n",
    "        print(f\"\\n Outputs saved to:\")\n",
    "        print(f\"   - {OUTPUT_PATH / 'price_distribution.png'}\")\n",
    "        print(f\"   - {OUTPUT_PATH / 'map_gwr_crime_coef.png'} (KEY)\")\n",
    "        print(f\"   - {OUTPUT_PATH / 'model_summary.csv'}\")\n",
    "        print(f\"   - {OUTPUT_PATH / 'gwr_results.geojson'}\")\n",
    "        \n",
    "    except FileNotFoundError as e:\n",
    "        print(f\" DATA ERROR: {e}\")\n",
    "        print(\"Make sure data/raw/ contains:\")\n",
    "        print(\"  - houseprices/ (pp-*.csv files)\")\n",
    "        print(\"  - crime/ (*.csv files)\")\n",
    "        print(\"  - geo/ (LSOA shapefile + postcode_directory.csv)\")\n",
    "        sys.exit(1)\n",
    "    except Exception as e:\n",
    "        print(f\" PIPELINE ERROR: {e}\")\n",
    "        import traceback\n",
    "        traceback.print_exc()\n",
    "        sys.exit(1)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
