{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aaa21827-b3fc-4d5f-9d3e-7f080f8861b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Visualization functions for exploratory analysis and model results.\"\"\"\n",
    "\n",
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import geopandas as gpd\n",
    "from typing import Dict, Any\n",
    "from src.config import OUTPUT_PATH\n",
    "\n",
    "# Set plotting style\n",
    "plt.style.use('default')\n",
    "sns.set_style(\"whitegrid\")\n",
    "plt.rcParams['figure.dpi'] = 100\n",
    "\n",
    "def plot_price_distribution(house_clean: pd.DataFrame, output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Plot histogram of house prices.\"\"\"\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    \n",
    "    ax.hist(house_clean['price'], bins=50, color='#ffcbcb', edgecolor='black', alpha=0.7)\n",
    "    ax.set_xlabel('Sale Price (£)', fontsize=12)\n",
    "    ax.set_ylabel('Number of Sales', fontsize=12)\n",
    "    ax.set_title('Distribution of House Prices in Bristol', fontsize=14, pad=12)\n",
    "    \n",
    "    # Format y-axis with thousands separator\n",
    "    ax.get_yaxis().set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:,.0f}'))\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'price_distribution.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: price_distribution.png\")\n",
    "\n",
    "def plot_crime_trends(crime_clean: pd.DataFrame, output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Plot crime trends by type over years.\"\"\"\n",
    "    # Aggregate by year and crime type\n",
    "    crime_pivot = crime_clean.pivot_table(\n",
    "        index='year', columns='Crime type', aggfunc='size', fill_value=0\n",
    "    )\n",
    "    \n",
    "    # Top 5 crime types\n",
    "    top_types = crime_clean['Crime type'].value_counts().head(5).index\n",
    "    \n",
    "    fig, ax = plt.subplots(figsize=(12, 6))\n",
    "    for crime_type in top_types:\n",
    "        if crime_type in crime_pivot.columns:\n",
    "            ax.plot(crime_pivot.index, crime_pivot[crime_type], \n",
    "                   marker='o', linewidth=2, label=crime_type)\n",
    "    \n",
    "    ax.set_xlabel('Year', fontsize=12)\n",
    "    ax.set_ylabel('Number of Crimes', fontsize=12)\n",
    "    ax.set_title('Crime Trends by Type in Bristol', fontsize=14, pad=12)\n",
    "    ax.legend(fontsize=9, frameon=True)\n",
    "    ax.grid(alpha=0.3)\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'crime_trends.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: crime_trends.png\")\n",
    "\n",
    "def plot_scatter_crime_price(reg_gdf: gpd.GeoDataFrame, output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Scatter plot: crime vs price (log-log scale).\"\"\"\n",
    "    fig, ax = plt.subplots(figsize=(8, 6))\n",
    "    \n",
    "    ax.scatter(reg_gdf['log_crime'], reg_gdf['log_median_price'], \n",
    "              s=30, alpha=0.6, color='darkorange', edgecolor='white', linewidth=0.5)\n",
    "    \n",
    "    ax.set_xlabel('log(Total Crimes)', fontsize=12)\n",
    "    ax.set_ylabel('log(Median House Price)', fontsize=12)\n",
    "    ax.set_title('Relationship between Crime and House Prices (Log Scale)', fontsize=14, pad=12)\n",
    "    ax.grid(alpha=0.3)\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'scatter_crime_price.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: scatter_crime_price.png\")\n",
    "\n",
    "def plot_map_median_price(reg_gdf: gpd.GeoDataFrame, output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Choropleth map of median house prices.\"\"\"\n",
    "    fig, ax = plt.subplots(1, 1, figsize=(10, 10))\n",
    "    \n",
    "    reg_gdf.plot(column='median_price', cmap='YlGnBu', legend=True, \n",
    "                linewidth=0.1, edgecolor='grey', ax=ax,\n",
    "                legend_kwds={'label': \"Median Price (£)\", 'shrink': 0.8})\n",
    "    \n",
    "    ax.set_title('Median House Price by LSOA - Bristol', fontsize=14)\n",
    "    ax.axis('off')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'map_median_price.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: map_median_price.png\")\n",
    "\n",
    "def plot_map_total_crime(reg_gdf: gpd.GeoDataFrame, output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Choropleth map of total crime counts.\"\"\"\n",
    "    fig, ax = plt.subplots(1, 1, figsize=(10, 10))\n",
    "    \n",
    "    reg_gdf.plot(column='total_crimes', cmap='Reds', legend=True, \n",
    "                linewidth=0.1, edgecolor='grey', ax=ax,\n",
    "                legend_kwds={'label': \"Total Crimes\", 'shrink': 0.8})\n",
    "    \n",
    "    ax.set_title('Total Crime by LSOA - Bristol', fontsize=14)\n",
    "    ax.axis('off')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'map_total_crime.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: map_total_crime.png\")\n",
    "\n",
    "def plot_ols_residual_map(reg_gdf: gpd.GeoDataFrame, ols_results: Dict[str, Any], output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Choropleth map of OLS residuals by LSOA.\"\"\"\n",
    "    # Attach residuals to GeoDataFrame\n",
    "    reg_gdf_with_res = reg_gdf.copy()\n",
    "    reg_gdf_with_res['ols_residuals'] = ols_results['residuals']\n",
    "    \n",
    "    fig, ax = plt.subplots(1, 1, figsize=(10, 10))\n",
    "    \n",
    "    reg_gdf_with_res.plot(column='ols_residuals', cmap='bwr', legend=True, \n",
    "                         linewidth=0.2, edgecolor='grey', ax=ax,\n",
    "                         legend_kwds={'label': \"OLS residuals (log price)\", 'shrink': 0.8})\n",
    "    \n",
    "    ax.set_title('OLS Residuals by LSOA - Bristol', fontsize=14)\n",
    "    ax.axis('off')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'map_ols_residuals.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: map_ols_residuals.png\")\n",
    "\n",
    "def plot_gwr_coefficient_map(reg_gdf: gpd.GeoDataFrame, gwr_results: Dict[str, Any], output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Map of local GWR crime coefficients.\"\"\"\n",
    "    if gwr_results is None:\n",
    "        print(\"No GWR results available\")\n",
    "        return\n",
    "    \n",
    "    # Add local coefficients to GeoDataFrame\n",
    "    reg_gdf_gwr = reg_gdf.copy()\n",
    "    reg_gdf_gwr['gwr_intercept'] = gwr_results['params'][:, 0]\n",
    "    reg_gdf_gwr['gwr_log_crime'] = gwr_results['params'][:, 1]  # Crime coefficient\n",
    "    reg_gdf_gwr['gwr_prop_flats'] = gwr_results['params'][:, 2]\n",
    "    reg_gdf_gwr['gwr_prop_leasehold'] = gwr_results['params'][:, 3]\n",
    "    \n",
    "    # Plot crime coefficient map\n",
    "    fig, ax = plt.subplots(1, 1, figsize=(10, 10))\n",
    "    \n",
    "    reg_gdf_gwr.plot(column='gwr_log_crime', cmap='bwr', legend=True, \n",
    "                    linewidth=0.2, edgecolor='grey', ax=ax,\n",
    "                    legend_kwds={'label': \"GWR Crime Coefficient\", 'shrink': 0.8})\n",
    "    \n",
    "    ax.set_title('Local Crime Effect on House Prices (GWR) - Bristol', fontsize=14)\n",
    "    ax.axis('off')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'map_gwr_crime_coef.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: map_gwr_crime_coef.png\")\n",
    "\n",
    "def plot_model_comparison(comparison_results: Dict[str, Any], output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Bar chart comparing OLS vs GWR metrics.\"\"\"\n",
    "    if comparison_results.get('comparison_table') is None:\n",
    "        print(\"No comparison results available\")\n",
    "        return\n",
    "    \n",
    "    comparison_df = comparison_results['comparison_table']\n",
    "    \n",
    "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))\n",
    "    \n",
    "    # R² comparison\n",
    "    metrics_to_plot = comparison_df[comparison_df['Metric'].isin(['R²', 'Adj R²'])]\n",
    "    x = np.arange(len(metrics_to_plot))\n",
    "    width = 0.35\n",
    "    \n",
    "    ax1.bar(x - width/2, metrics_to_plot['OLS'], width, label='OLS', alpha=0.8)\n",
    "    ax1.bar(x + width/2, metrics_to_plot['GWR'], width, label='GWR', alpha=0.8)\n",
    "    ax1.set_xlabel('Metrics')\n",
    "    ax1.set_ylabel('R²')\n",
    "    ax1.set_title('Model Fit Comparison (R²)')\n",
    "    ax1.set_xticks(x)\n",
    "    ax1.set_xticklabels(metrics_to_plot['Metric'])\n",
    "    ax1.legend()\n",
    "    \n",
    "    # AICc comparison\n",
    "    ax2.bar(['OLS', 'GWR'], comparison_df[comparison_df['Metric'] == 'AICc'][['OLS', 'GWR']].values[0], \n",
    "            color=['red', 'blue'], alpha=0.8)\n",
    "    ax2.set_ylabel('AICc (lower = better)')\n",
    "    ax2.set_title('Model Fit Comparison (AICc)')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig(output_path / 'model_comparison.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(\"Saved: model_comparison.png\")\n",
    "\n",
    "# Convenience function to run all plots\n",
    "def create_visualization_suite(reg_gdf: gpd.GeoDataFrame, results: Dict[str, Any], \n",
    "                              house_clean: pd.DataFrame, crime_clean: pd.DataFrame,\n",
    "                              output_path: Path = OUTPUT_PATH):\n",
    "    \"\"\"Run all visualizations\"\"\"\n",
    "    print(\"\\n🎨 Creating Visualization Suite...\")\n",
    "    \n",
    "    # EDA plots\n",
    "    plot_price_distribution(house_clean, output_path)\n",
    "    plot_crime_trends(crime_clean, output_path)\n",
    "    plot_scatter_crime_price(reg_gdf, output_path)\n",
    "    plot_map_median_price(reg_gdf, output_path)\n",
    "    plot_map_total_crime(reg_gdf, output_path)\n",
    "    \n",
    "    # Model diagnostics\n",
    "    plot_ols_residual_map(reg_gdf, results['ols_results'], output_path)\n",
    "    \n",
    "    # GWR results\n",
    "    plot_gwr_coefficient_map(reg_gdf, results.get('gwr_results'), output_path)\n",
    "    \n",
    "    # Model comparison\n",
    "    plot_model_comparison(results['comparison_results'], output_path)\n",
    "    \n",
    "    print(f\"\\n✅ All plots saved to {output_path}\")\n",
    "    print(\"Files created:\")\n",
    "    print(\"  - price_distribution.png\")\n",
    "    print(\"  - crime_trends.png\")\n",
    "    print(\"  - scatter_crime_price.png\")\n",
    "    print(\"  - map_median_price.png\")\n",
    "    print(\"  - map_total_crime.png\")\n",
    "    print(\"  - map_ols_residuals.png\")\n",
    "    print(\"  - map_gwr_crime_coef.png\")\n",
    "    print(\"  - model_comparison.png\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
